### ISSUE TITLE
AlexNet modellieren

### ISSUE THREAD

**Issue by EvgenyKusmenko** [EmbeddedMontiArc/CNNArchLang#1]
- MXNet
- Caffe
- (Caffe2) was müsste man im Caffe modell ändern
- ggf weitere

**Comment by EvgenyKusmenko** [comment]
in CNNArchLang

**Comment by Thomas26791** [comment]
MxNet: [https://git.rwth-aachen.de/thesis/ma_timmermanns/blob/master/vorbereitung/code%20examples/alexnet_mxnet.py](url)
Caffe: [https://git.rwth-aachen.de/thesis/ma_timmermanns/blob/master/vorbereitung/code%20examples/alexnet_caffe.prototxt](url)
Keras: [https://git.rwth-aachen.de/thesis/ma_timmermanns/blob/master/vorbereitung/code%20examples/alexnet_keras.py](url)
CNNArch: [https://github.com/EmbeddedMontiArc/CNNArchLang/blob/master/src/test/resources/Alexnet.cnna](url)
