### ISSUE TITLE
Build fixen

### ISSUE THREAD

**Issue by EvgenyKusmenko** [EmbeddedMontiArc/CNNArchLang#4]
JUnit anschauen, erste Tests schreiben (Übernehmen der vohandenen Sprachtests)
eigenen Branch anlegen

**Comment by Thomas26791** [comment]
fixed.
The repository had to be added to coveralls in https://coveralls.io/repos/new

**Comment by vonwenckstern** [comment]
ask @strepkov to add it to coveralls.io and ask @sschneiders to code climate

and then please add the badges to your project

**Comment by Thomas26791** [comment]
I was able to add it to coveralls myself.
Should i still ask?

**Comment by vonwenckstern** [comment]
No, then just add the badgets in your repo and to  
https://github.com/EmbeddedMontiArc/Documentation/blob/master/RepoStatus.md
Zitat von Thomas Timmermanns <notifications@github.com>:

**Comment by EvgenyKusmenko** [comment]
fixed
